# Instalações e importações

In [1]:
import numpy as np
np.__version__

'1.26.4'

In [2]:
import scipy
scipy.__version__

'1.14.1'

# Matrizes

In [3]:
matrix = np.array(
    [[1, 1, 2, 2, 10, 127.35],
     [2, 2, 2, 1, 10, 128.10],
     [2, 1, 2, 2, 10, 134.85],
     [2, 1, 2, 1, 10, 119.85]]
)

In [4]:
matrix.ndim

2

In [5]:
matrix.shape

(4, 6)

In [6]:
matrix.size

24

## Normas

In [7]:
np.linalg.norm(matrix)

256.16826013384247

In [8]:
np.linalg.norm(matrix, ord = 2)

256.16224823752526

## Matriz transposta

In [9]:
matrix

array([[  1.  ,   1.  ,   2.  ,   2.  ,  10.  , 127.35],
       [  2.  ,   2.  ,   2.  ,   1.  ,  10.  , 128.1 ],
       [  2.  ,   1.  ,   2.  ,   2.  ,  10.  , 134.85],
       [  2.  ,   1.  ,   2.  ,   1.  ,  10.  , 119.85]])

In [10]:
np.transpose(matrix)

array([[  1.  ,   2.  ,   2.  ,   2.  ],
       [  1.  ,   2.  ,   1.  ,   1.  ],
       [  2.  ,   2.  ,   2.  ,   2.  ],
       [  2.  ,   1.  ,   2.  ,   1.  ],
       [ 10.  ,  10.  ,  10.  ,  10.  ],
       [127.35, 128.1 , 134.85, 119.85]])

In [11]:
matrix.transpose()

array([[  1.  ,   2.  ,   2.  ,   2.  ],
       [  1.  ,   2.  ,   1.  ,   1.  ],
       [  2.  ,   2.  ,   2.  ,   2.  ],
       [  2.  ,   1.  ,   2.  ,   1.  ],
       [ 10.  ,  10.  ,  10.  ,  10.  ],
       [127.35, 128.1 , 134.85, 119.85]])

In [12]:
matrix.T

array([[  1.  ,   2.  ,   2.  ,   2.  ],
       [  1.  ,   2.  ,   1.  ,   1.  ],
       [  2.  ,   2.  ,   2.  ,   2.  ],
       [  2.  ,   1.  ,   2.  ,   1.  ],
       [ 10.  ,  10.  ,  10.  ,  10.  ],
       [127.35, 128.1 , 134.85, 119.85]])

## Matriz simétrica

In [13]:
sym_matrix = np.array(
    [[1, 3, 2, 5],
     [3, 2, 8, 1],
     [2, 8, 6, 7],
     [5, 1, 7, 4]]
)

In [14]:
scipy.linalg.issymmetric(sym_matrix)

True

Também podemos checar através da propriedade $A = A^T$:

In [15]:
np.all(sym_matrix == sym_matrix.T)

True

## Matriz diagonal

In [16]:
diag_matrix = np.array(
    [[1, 0, 0, 0],
     [0, 2, 0, 0],
     [0, 0, 6, 0],
     [0, 0, 0, 4]]
)

In [17]:
diagonal_elements = np.diag(diag_matrix)
diagonal_elements

array([1, 2, 6, 4])

In [18]:
new_diag_matrix = np.diag(diagonal_elements)
new_diag_matrix

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 4]])

In [19]:
np.all(diag_matrix == new_diag_matrix)

True

Propriedade das matrizes diagonais: <br>
$\text{diag}(\vec{a})^{-1} = \text{diag}([a_1^{-1}, \ldots, a_n^{-1}])$

In [20]:
diag_elements_reciprocal = np.reciprocal(diagonal_elements.astype(float))
diag_elements_reciprocal

array([1.        , 0.5       , 0.16666667, 0.25      ])

In [21]:
diag_matrix_inverse = np.linalg.inv(diag_matrix)
diag_matrix_inverse

array([[1.        , 0.        , 0.        , 0.        ],
       [0.        , 0.5       , 0.        , 0.        ],
       [0.        , 0.        , 0.16666667, 0.        ],
       [0.        , 0.        , 0.        , 0.25      ]])

In [22]:
np.all(diag_elements_reciprocal == np.diag(diag_matrix_inverse))

True

## Matriz identidade

In [23]:
np.identity(n = 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.identity(n = 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.all(np.diag(np.identity(n = 4) == 1))

True

## Matriz inversa

In [26]:
sym_matrix

array([[1, 3, 2, 5],
       [3, 2, 8, 1],
       [2, 8, 6, 7],
       [5, 1, 7, 4]])

In [27]:
sym_matrix_inv = np.linalg.inv(sym_matrix)
sym_matrix_inv

array([[-0.92165899, -0.57603687,  0.41935484,  0.56221198],
       [-0.57603687, -0.23502304,  0.38709677,  0.10138249],
       [ 0.41935484,  0.38709677, -0.22580645, -0.22580645],
       [ 0.56221198,  0.10138249, -0.22580645, -0.08294931]])

Checando a propriedade $A^{-1}A = I$:

In [28]:
np.dot(sym_matrix, sym_matrix_inv)

array([[ 1.00000000e+00,  1.24900090e-16,  8.32667268e-17,
         2.77555756e-17],
       [ 1.44328993e-15,  1.00000000e+00, -6.93889390e-16,
        -4.16333634e-16],
       [ 7.77156117e-16,  4.16333634e-17,  1.00000000e+00,
        -1.38777878e-16],
       [ 0.00000000e+00, -2.77555756e-16,  3.33066907e-16,
         1.00000000e+00]])

In [29]:
np.allclose(np.dot(sym_matrix, sym_matrix_inv), np.identity(4))

True

In [30]:
sing_matrix = np.array(
        [[1, 3, 2,  5], # ----|
         [3, 2, 8,  1], #     x2
         [2, 6, 4, 10], # <---|
         [5, 1, 7,  4]]
)

In [32]:
if np.linalg.det(sing_matrix) != 0:
    inv = np.linalg.inv(sing_matrix)
else:
    print("Matriz singular – não tem inversa.")

Matriz singular – não tem inversa.


In [52]:
sing_matrix_inv = np.linalg.pinv(sing_matrix)
sing_matrix_inv

array([[-0.02134168, -0.14181439, -0.04268335,  0.22419187],
       [ 0.03524505,  0.16579771,  0.07049009, -0.21063608],
       [-0.00389294,  0.15328467, -0.00778589, -0.04379562],
       [ 0.02467848, -0.13242961,  0.04935697,  0.09906152]])

In [53]:
matrix

array([[  1.  ,   1.  ,   2.  ,   2.  ,  10.  , 127.35],
       [  2.  ,   2.  ,   2.  ,   1.  ,  10.  , 128.1 ],
       [  2.  ,   1.  ,   2.  ,   2.  ,  10.  , 134.85],
       [  2.  ,   1.  ,   2.  ,   1.  ,  10.  , 119.85]])

In [37]:
# Verifica se a matriz é quadrada
if matrix.shape[0] == matrix.shape[1]:
    if not np.isclose(np.linalg.det(matrix), 0.0):
        inv = np.linalg.inv(matrix)
        print("Matriz inversa:\n", inv)
    else:
        print("Matriz singular – não tem inversa.")
        pinv = np.linalg.pinv(matrix)
        print("Pseudo-inversa:\n", pinv)
else:
    print("Matriz não quadrada – calculando a pseudo-inversa.")
    pinv = np.linalg.pinv(matrix)
    print("Pseudo-inversa:\n", pinv)

Matriz não quadrada – calculando a pseudo-inversa.
Pseudo-inversa:
 [[-0.89264595 -0.13513244  0.63533039  0.37824551]
 [ 0.11808946  0.85135432 -0.40113657 -0.58392994]
 [ 0.06092331 -0.04750463 -0.13399241  0.13683291]
 [ 0.21470811 -0.27026488  0.27066078 -0.24350898]
 [ 0.30461655 -0.23752317 -0.66996205  0.68416453]
 [-0.01431387  0.01801766  0.04862261 -0.05043273]]


In [45]:
# Teste de produto interno para obter indentidade
np.dot(matrix, np.linalg.pinv(matrix)).round()

array([[ 1.,  0., -0., -0.],
       [-0.,  1., -0.,  0.],
       [-0.,  0.,  1.,  0.],
       [-0.,  0., -0.,  1.]])

## Determinante

In [42]:
sym_matrix

array([[1, 3, 2, 5],
       [3, 2, 8, 1],
       [2, 8, 6, 7],
       [5, 1, 7, 4]])

In [43]:
np.linalg.det(sym_matrix)

216.99999999999986

In [61]:
sing_matrix

array([[ 1,  3,  2,  5],
       [ 3,  2,  8,  1],
       [ 2,  6,  4, 10],
       [ 5,  1,  7,  4]])

In [63]:
np.linalg.det(sing_matrix)

0.0

## Matriz ortogonal

> *Os vetores que representam as linhas, ou os vetores que representam as colunas, são todos ortonormais (ou seja, ortogonais e unitários).*

In [64]:
orthogonal_matrix = np.array([
    [ 1/2, -1/2,  1/2,  1/2],
    [ 1/2,  1/2, -1/2,  1/2],
    [-1/2,  1/2,  1/2,  1/2],
    [ 1/2,  1/2,  1/2, -1/2]
])

In [65]:
np.linalg.norm(orthogonal_matrix, axis = 0)

array([1., 1., 1., 1.])

In [66]:
np.linalg.norm(orthogonal_matrix, axis = 1)

array([1., 1., 1., 1.])

$A^T A = AA^T = I$

In [67]:
np.dot(orthogonal_matrix.T, orthogonal_matrix)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [68]:
np.dot(orthogonal_matrix, orthogonal_matrix.T)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [69]:
np.identity(n = 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

$A^T = A^{-1}I = A^{-1}$

In [70]:
orthogonal_matrix.T

array([[ 0.5,  0.5, -0.5,  0.5],
       [-0.5,  0.5,  0.5,  0.5],
       [ 0.5, -0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5, -0.5]])

In [71]:
np.linalg.inv(orthogonal_matrix)

array([[ 0.5,  0.5, -0.5,  0.5],
       [-0.5,  0.5,  0.5,  0.5],
       [ 0.5, -0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5, -0.5]])

In [73]:
np.all(orthogonal_matrix.T == np.linalg.inv(orthogonal_matrix))

True