# Instalações e importações

In [10]:
import numpy as np
np.__version__

'1.26.4'

In [11]:
import plotly
import plotly.graph_objects as go
plotly.__version__

'6.0.1'

# Operações com escalares

In [12]:
np.array([1, 2, 3]) + 4

array([5, 6, 7])

In [13]:
np.array([[9, 8, 7],
          [6, 5, 4],
          [3, 2, 1]]) - 5

array([[ 4,  3,  2],
       [ 1,  0, -1],
       [-2, -3, -4]])

In [14]:
np.array([[9, 8, 7],
          [6, 5, 4],
          [3, 2, 1]]) * 2

array([[18, 16, 14],
       [12, 10,  8],
       [ 6,  4,  2]])

In [15]:
np.array([[8],
          [10],
          [12]]) / 2

array([[4.],
       [5.],
       [6.]])

# Operações de redução

In [16]:
np.sum(np.array([1, 2, 3]))

6

In [17]:
np.array([1, 2, 3]).sum()

6

In [18]:
array = np.array([[9, 8, 7],
                  [6, 5, 4],
                  [3, 2, 1]])

In [19]:
np.sum(array)

45

In [20]:
np.sum(array, axis = 0)

array([18, 15, 12])

In [21]:
np.sum(array, axis = 1)

array([24, 15,  6])

In [22]:
np.mean(array), np.sum(array) / array.size

(5.0, 5.0)

In [23]:
np.mean(array, axis = 0)

array([6., 5., 4.])

In [24]:
np.mean(array, axis = 1)

array([8., 5., 2.])

In [26]:
# produto de todos os elementos de dentro do vetor ou matriz 
np.prod(array)

362880

In [27]:
np.min(array)

1

In [28]:
np.max(array)

9

# Operações entre tensores

## Elemento a elemento

In [29]:
np.array([2, 1, 0]) + np.array([3, 4, 5])

array([5, 5, 5])

In [30]:
array_1 = np.array([[9, 8],
                    [7, 6],
                    [5, 4]])
array_2 = np.array([[1, 2],
                    [3, 4],
                    [5, 6]])
array_1 - array_2

array([[ 8,  6],
       [ 4,  2],
       [ 0, -2]])

In [31]:
array_1 = np.array([[1, 3],
                    [4, 6],
                    [7, 9]])
array_2 = np.array([[2, 2],
                    [3, 3],
                    [4, 4]])
array_1 * array_2

array([[ 2,  6],
       [12, 18],
       [28, 36]])

In [32]:
array_1 = np.array([10, 9, 8])
array_2 = np.array([2, 3, 4])
array_1 / array_2

array([5., 3., 2.])

## Multiplicação matricial

In [33]:
array_1 = np.array([[1, 3],
                    [4, 6],
                    [7, 9]])
array_2 = np.array([[2, 2],
                    [3, 3],
                    [4, 4]])

In [34]:
array_1.shape, array_2.shape

((3, 2), (3, 2))

In [38]:

def multiplicar_automaticamente(a, b):
    """
    Tenta multiplicar duas matrizes. Se a multiplicação direta não for possível,
    tenta multiplicar com a transposta de b.
    """
    try:
        # Tenta multiplicar diretamente
        return np.matmul(a, b)
    except ValueError:
        # Se falhar, tenta com a transposta de b
        print("Multiplicação direta falhou, tentando com a transposta de b.")
        try:
            return np.matmul(a, b.T)
        except ValueError:
            return "Nenhuma multiplicação possível, nem mesmo com a transposta."


In [39]:
multiplicar_automaticamente(array_1, array_2)

Multiplicação direta falhou, tentando com a transposta de b.


array([[ 8, 12, 16],
       [20, 30, 40],
       [32, 48, 64]])

In [42]:
array_2 = np.array([[2, 3, 4],
                    [2, 3, 4]])
array_2.shape

(2, 3)

In [43]:
np.matmul(array_1, array_2)

array([[ 8, 12, 16],
       [20, 30, 40],
       [32, 48, 64]])

## Produto Escalar

In [46]:
array_1 = np.array([2, 1, 0])
array_2 = np.array([3, 4, 5])

In [47]:
np.dot(array_1, array_2)

10

Verificando a proprieade $\vec{x} \cdot \vec{x} = ||\vec{x}||^2$:

In [48]:
np.dot(array_1, array_1)

5

In [49]:
np.linalg.norm(array_1)**2

5.000000000000001

## Regra de cosseno

$\cos \theta = \frac{\vec{a} \cdot \vec{b}}{ab}$

Primeiro calculamos o `dot_product` $\vec{a} \cdot \vec{b}$:

In [50]:
dot_product = np.dot(array_1, array_2)
dot_product

10

Agora calculamos o comprimento `len` dos dois vetores, `array_1` e `array_2` ($a$ e $b$):

In [51]:
len_1 = np.linalg.norm(array_1)
len_2 = np.linalg.norm(array_2)
len_1, len_2

(2.23606797749979, 7.0710678118654755)

Agora colocamos tudo na fórmula da regra do cosseno.

In [53]:
cos_theta = dot_product / (len_1 * len_2)
cos_theta

0.6324555320336758

In [54]:
np.arccos(cos_theta)

0.8860771237926138

In [55]:
np.rad2deg(np.arccos(cos_theta))

50.76847951640775

In [56]:
vectors = [array_1, array_2]

fig = go.Figure()

for i, vec in enumerate(vectors, start=1):
  #print(i)
  fig.add_trace(go.Scatter3d(
      x = [0, vec[0]],
      y = [0, vec[1]],
      z = [0, vec[2]],
      mode = "lines",
      line = dict(width = 3),
      name = 'array_' + str(i)
  ))

fig.show()