# Instalações e importações

In [1]:
import numpy as np
np.__version__

'1.26.4'

In [2]:
import plotly
import plotly.graph_objects as go
plotly.__version__

'5.24.1'

# Operações com escalares

In [4]:
np.array([1, 2, 3]) + 4

array([5, 6, 7])

In [6]:
np.array([[9, 8, 7],
          [6, 5, 4],
          [3, 2, 1]]) - 5

array([[ 4,  3,  2],
       [ 1,  0, -1],
       [-2, -3, -4]])

In [7]:
np.array([[9, 8, 7],
          [6, 5, 4],
          [3, 2, 1]]) * 2

array([[18, 16, 14],
       [12, 10,  8],
       [ 6,  4,  2]])

In [8]:
np.array([[8],
          [10],
          [12]]) / 2

array([[4.],
       [5.],
       [6.]])

# Operações de redução

In [10]:
np.sum(np.array([1, 2, 3]))

6

In [11]:
np.array([1, 2, 3]).sum()

6

In [12]:
array = np.array([[9, 8, 7],
                  [6, 5, 4],
                  [3, 2, 1]])

In [13]:
np.sum(array)

45

In [14]:
np.sum(array, axis = 0)

array([18, 15, 12])

In [15]:
np.sum(array, axis = 1)

array([24, 15,  6])

In [17]:
np.mean(array), np.sum(array) / array.size

(5.0, 5.0)

In [18]:
np.mean(array, axis = 0)

array([6., 5., 4.])

In [19]:
np.mean(array, axis = 1)

array([8., 5., 2.])

In [20]:
np.prod(array)

362880

In [21]:
np.min(array)

1

In [22]:
np.max(array)

9

# Operações entre tensores

## Elemento a elemento

In [23]:
np.array([2, 1, 0]) + np.array([3, 4, 5])

array([5, 5, 5])

In [24]:
array_1 = np.array([[9, 8],
                    [7, 6],
                    [5, 4]])
array_2 = np.array([[1, 2],
                    [3, 4],
                    [5, 6]])
array_1 - array_2

array([[ 8,  6],
       [ 4,  2],
       [ 0, -2]])

In [25]:
array_1 = np.array([[1, 3],
                    [4, 6],
                    [7, 9]])
array_2 = np.array([[2, 2],
                    [3, 3],
                    [4, 4]])
array_1 * array_2

array([[ 2,  6],
       [12, 18],
       [28, 36]])

In [26]:
array_1 = np.array([10, 9, 8])
array_2 = np.array([2, 3, 4])
array_1 / array_2

array([5., 3., 2.])

## Multiplicação matricial

In [27]:
array_1 = np.array([[1, 3],
                    [4, 6],
                    [7, 9]])
array_2 = np.array([[2, 2],
                    [3, 3],
                    [4, 4]])

In [28]:
array_1.shape, array_2.shape

((3, 2), (3, 2))

In [29]:
np.matmul(array_1, array_2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [30]:
array_2 = np.array([[2, 3, 4],
                    [2, 3, 4]])
array_2.shape

(2, 3)

In [31]:
np.matmul(array_1, array_2)

array([[ 8, 12, 16],
       [20, 30, 40],
       [32, 48, 64]])

## Produto vetorial/escalar/interno

In [32]:
array_1 = np.array([2, 1, 0])
array_2 = np.array([3, 4, 5])

In [33]:
np.dot(array_1, array_2)

10

Verificando a proprieade $\vec{x} \cdot \vec{x} = ||\vec{x}||^2$:

In [34]:
np.dot(array_1, array_1)

5

In [36]:
np.linalg.norm(array_1)**2

5.000000000000001

## Regra de cosseno

$\cos \theta = \frac{\vec{a} \cdot \vec{b}}{ab}$

Primeiro calculamos o `dot_product` $\vec{a} \cdot \vec{b}$:

In [37]:
dot_product = np.dot(array_1, array_2)
dot_product

10

Agora calculamos o comprimento `len` dos dois vetores, `array_1` e `array_2` ($a$ e $b$):

In [38]:
len_1 = np.linalg.norm(array_1)
len_2 = np.linalg.norm(array_2)
len_1, len_2

(2.23606797749979, 7.0710678118654755)

Agora colocamos tudo na fórmula da regra do cosseno.

In [39]:
cos_theta = dot_product / (len_1 * len_2)
cos_theta

0.6324555320336758

In [40]:
np.arccos(cos_theta)

0.8860771237926138

In [41]:
np.rad2deg(np.arccos(cos_theta))

50.76847951640775

In [43]:
vectors = [array_1, array_2]

fig = go.Figure()

for i, vec in enumerate(vectors, start=1):
  #print(i)
  fig.add_trace(go.Scatter3d(
      x = [0, vec[0]],
      y = [0, vec[1]],
      z = [0, vec[2]],
      mode = "lines",
      line = dict(width = 3),
      name = 'array_' + str(i)
  ))

fig.show()